apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: minimum-parakeet-go 
  janus-idp.io/tekton: minimum-parakeet-go
  backstage.io/kubernetes-id: minimum-parakeet-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: minimum-parakeet-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  